import { getUserFromCookies } from "@/helper";
import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { redirect } from "next/navigation";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blog Exploring",
  description: "Generated by Saurabh Kumar",
};
export default async function layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUserFromCookies();
  if (user) {
    redirect("/");
  }
  return (
    <div>
      {children}
    </div>
  );
}
