import Header from '@/components/Header'
import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Major Project",
  description: "Generated by create next app",
};
export default function layout({children}:{
    children: React.ReactNode
}) {
  return (
    <div>
        <Header/>
      {children}
    </div>
  )
}
